apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: storageos-operator
  name: storageos-operator
  namespace: storageos
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: storageos-operator
