apiVersion: config.storageos.com/v1
kind: OperatorConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: storageos-operator-lease
webhookCertRefreshInterval: 15m
webhookServiceName: storageos-operator-webhook-service
webhookSecretRef: storageos-operator-webhook-secret
validatingWebhookConfigRef: storageos-operator-validating-webhook-configuration
