apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageos:operator:scheduler-extender
rules:
- apiGroups: ["events.k8s.io"]
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups: ["scheduling.k8s.io"]
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
