# permissions for end users to view storageosclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageos:cluster-viewer
rules:
- apiGroups:
  - storageos.com
  resources:
  - storageosclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storageos.com
  resources:
  - storageosclusters/status
  verbs:
  - get
