
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: storageos-operator-validating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: storageos-operator-webhook
      namespace: storageos
      path: /validate-storageoscluster
  failurePolicy: Fail
  name: cluster-validator.storageos.com
  rules:
  - apiGroups:
    - storageos.com
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - storageosclusters
  sideEffects: None
