
apiVersion: v1
kind: Service
metadata:
  name: storageos-operator-webhook
  namespace: storageos
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: storageos-operator
