apiVersion: v1
kind: Service
metadata:
  name: storageos
  labels:
    app: storageos
spec:
  clusterIP: 10.99.207.226
  ports:
  - name: storageos
    port: 5705
    protocol: TCP
    targetPort: 5705
  selector:
    app: storageos
    kind: daemonset
  sessionAffinity: None
  type: ClusterIP
