apiVersion: storageos.com/v1
kind: StorageOSCluster
metadata:
  name: default
spec:
  # Add fields here
  secretRefName: storageos-api
  storageClassName: "storageos"
  kvBackend:
    address: "etcd-client:2379"
    # address: "etcd-client.default.svc.cluster.local:2379"
