
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: portal-manager
  name: storageos:proxy:portal-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageos:proxy:portal-manager
subjects:
- kind: ServiceAccount
  name: storageos-portal-manager
  namespace: portal-manager-system
