
apiVersion: v1
data:
  c9a7c661-efa6-47ac-9828-db09af72ca15.key: SU9UX0NPUkVfU1NMX0tFWQ==
kind: Secret
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: portal-manager
  name: iot-core-ssl
  namespace: portal-manager-system
type: Opaque
