
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: portal-manager
    control-plane: storageos-portal-manager
  name: storageos-portal-manager
  namespace: portal-manager-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: storageos
    app.kubernetes.io/component: portal-manager
    control-plane: storageos-portal-manager
