apiVersion: v1
kind: Service
metadata:
  name: storageos-webhook
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 9443
  sessionAffinity: None
  selector:
    app.kubernetes.io/component: storageos-api-manager
  type: ClusterIP
