apiVersion: v1
kind: Service
metadata:
  name: storageos-node
spec:
  ports:
  - name: storageos
    port: 5705
    protocol: TCP
    targetPort: 5705
  sessionAffinity: None
  selector:
    app: storageos
    app.kubernetes.io/component: control-plane
  type: ClusterIP
