apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storageos:scheduler-extender
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageos:scheduler-extender
subjects:
- kind: ServiceAccount
  name: storageos-scheduler-sa
  # NOTE: Find out how to make this namespace reference dynamic.
  namespace: default
