apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-scheduler
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - args:
        - kube-scheduler
        - --leader-elect=true
        - --scheduler-name=storageos-scheduler
        - --policy-configmap=storageos-scheduler-policy
        - --policy-configmap-namespace=default
        - --lock-object-name=storageos-scheduler
        - -v=4
        image: k8s.gcr.io/kube-scheduler:v1.19.0
        imagePullPolicy: IfNotPresent
        name: storageos-scheduler
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: storageos-scheduler-sa
      serviceAccountName: storageos-scheduler-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
