apiVersion: v1
data:
  policy.cfg: |2

        {
          "kind" : "Policy",
          "apiVersion" : "v1",
          "predicates" : [
            {"name" : "PodFitsHostPorts"},
            {"name" : "PodFitsResources"},
            {"name" : "NoDiskConflict"},
            {"name" : "MatchNodeSelector"},
            {"name" : "HostName"}
          ],
          "extenders" : [{
            "urlPrefix": "http://storageos.kube-system.svc:5705/v2/k8s/scheduler",
            "filterVerb": "filter",
            "prioritizeVerb": "prioritize",
            "weight": 1,
            "enableHttps": false,
            "nodeCacheCapable": false
          }]
        }
kind: ConfigMap
metadata:
  labels:
    app: storageos
  name: storageos-scheduler-policy
