apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storageos
  name: storageos:csi-attacher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageos:csi-attacher
subjects:
- kind: ServiceAccount
  name: storageos-csi-helper-sa
  # NOTE: Find out how to make this namespace reference dynamic.
  namespace: default
