apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-csi-helper
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - args:
        - --v=5
        - --provisioner=storageos
        - --csi-address=$(ADDRESS)
        - --extra-create-metadata
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: csi-provisioner
        imagePullPolicy: IfNotPresent
        name: csi-external-provisioner
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: csi-attacher
        imagePullPolicy: IfNotPresent
        name: csi-external-attacher
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: csi-resizer
        imagePullPolicy: IfNotPresent
        name: csi-external-resizer
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: storageos-csi-helper-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/storageos
          type: DirectoryOrCreate
        name: plugin-dir
