apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-csi-helper
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - args:
        - --v=5
        - --provisioner=storageos
        - --csi-address=$(ADDRESS)
        - --extra-create-metadata
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: storageos/csi-provisioner:v1.6.0-patched
        imagePullPolicy: IfNotPresent
        name: csi-external-provisioner
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: quay.io/k8scsi/csi-attacher:v2.2.0
        imagePullPolicy: IfNotPresent
        name: csi-external-attacher
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: quay.io/k8scsi/csi-resizer:v0.5.0
        imagePullPolicy: IfNotPresent
        name: csi-external-resizer
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: storageos-csi-helper-sa
      serviceAccountName: storageos-csi-helper-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/storageos
          type: DirectoryOrCreate
        name: plugin-dir
