name: Publish develop image

on:
  push:
    branches:
      - main

env:
  IMG: storageos/operator:develop

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Build container image
        run: make docker-build
      - name: Push container image
        run: make docker-push
