name: Publish feature image

on:
  workflow_dispatch:
    # Enable manual trigger of this action.
    inputs:
      tagPostfix:
        description: Image tag postfix.
        default: ""
        required: false

env:
  IMG: storageos/operator:feature-${{ github.head_ref }}${{ github.event.inputs.tagPostfix }}
  MANIFESTS_IMG: storageos/operator-manifests:feature-${{ github.head_ref }}${{ github.event.inputs.tagPostfix }}

jobs:
  publish-feature-image:
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Build container image
        run: make docker-build
      - name: Push container image
        run: make docker-push
  publish-feature-manifests-image:
    runs-on: ubuntu-latest
    name: Publish manifests container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Run manifests image build
        run: make docker-build-manifests
      - name: Push manifests container image
        run: docker push ${{ env.MANIFESTS_IMG }}
